name: celfonephonebookapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Flutter localization support
  flutter_localizations:
    sdk: flutter

  # Common packages
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.9.1
  lottie: ^3.3.1
  loading_animation_widget: ^1.3.0
  url_launcher: ^6.3.2
  carousel_slider: ^5.1.1
  image_picker: ^1.2.0
  intl: ^0.20.2
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.1
  font_awesome_flutter: ^10.7.0
  percent_indicator: ^4.2.3
  google_mlkit_text_recognition: ^0.14.0
  google_mlkit_commons: ^0.9.0
  animations: ^2.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/animations/
    - assets/images/
    - assets/translations/
